name: Scheduled weekly run
# Matrix workflow using re-usable github actions

on:
  schedule:
    # This cron job runs at 1:16 AM every 7th day of the month, every month of the year.
    - cron: '16 1 */7 * *'

jobs:
  module_template_71x_nightly:
    if: always()
    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v4
    with:
      testplan: '~/defaults/7.2.x.yaml,~/defaults/scheduled.yaml,~/module-template.yaml'
      runs_on: '"ubuntu-latest"'
      defaults: 'v4'
      plan_folder: '.github/oxid-esales'
      use_scheduled_slack_channel: true
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      CACHE_ENDPOINT: ${{ secrets.CACHE_ENDPOINT }}
      CACHE_ACCESS_KEY: ${{ secrets.CACHE_ACCESS_KEY }}
      CACHE_SECRET_KEY: ${{ secrets.CACHE_SECRET_KEY }}
      enterprise_github_token: ${{ secrets.enterprise_github_token }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_SCHEDULED_WEBHOOK_URL: ${{ secrets.SLACK_SCHEDULED_WEBHOOK_URL }}
